spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ridesharing_users

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: B374A26A71490437AA024E4FADD5B497FDFF1A8EA6FF12F6FB65AF2720B59CCF
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days