package com.ridesharing.core.model;

public enum NotificationType {
    RIDE_INITIATED, DRIVER_DECLINED, DRIVER_APPROVED, REQUEST_PENDING, DRIVER_LOCATION, RIDER_LOCATION,
    RIDER_DISCONNECTED, CLIENT_DISCONNECTED, DRIVER_DISCONNECTED, DRIVER_NOT_FOUND
}
