spring:
  application:
    name: location-service

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  config:
    redis:
      host: "127.0.0.1"
      port: 6379
      password: